window.I18N = {
  lang(){ return Game?.state?.settings?.language || localStorage.getItem('cityInATabLang') || 'en'; },
  strings:{
    en:{
      build:'Build', buildHint:'Click a tile after choosing', cityPulse:'City Pulse', growthStage:'Growth Stage',
      mayorDesk:"Mayor's Desk", policyDecision:'Policy Decision', nextBrief:'Next brief soon', nextPolicyAt:'Next policy · {n} pop', allPoliciesHandled:'All policy milestones reached', noDecision:'No urgent decision', noDecisionText:'Your staff will bring policy choices as the city evolves.',
      megaProjects:'Mega Projects', megaSub:'City-defining investments', pause:'Pause', resume:'Resume', settings:'Settings', howToPlay:'How to Play', liveStatus:'LIVE {n}×', pausedStatus:'PAUSED', pausedToast:'Simulation paused', pausedToastText:'Time, income and population growth are frozen.', resumedToast:'Simulation resumed', resumedToastText:'The city is moving again.', speedChanged:'Game speed changed', speedOne:'Simulation is running at 1×.', speedTwo:'Simulation is running at 2×.',
      bulldoze:'Bulldoze', center:'Center', fitCity:'Fit City', normalZoom:'Normal Zoom', saveCityImage:'Save City Image', imageSaved:'City image saved', imageSaveFailed:'Could not save city image', versionLabel:'Version', expandLand:'Expand Land', landMax:'Land Maxed', expandLandCost:'Expand {n}×{n} · ${cost}', expandLandLocked:'Land · {n} pop', expandLandTip:'Expand to {n}×{n}. Costs ${cost}; requires {pop} population.', landLocked:'Expansion locked', landExpanded:'City limits expanded', landExpandedText:'The map is now {n} × {n}.', cityExpansion:'CITY EXPANSION', expandTo:'Expand to {n} × {n}?', expandConfirm:'Purchase new land for ${cost}. Your existing city stays centered inside the larger {n} × {n} map.', buyLand:'Buy Land', cancel:'Cancel', placing:'Placing {name} — choose an empty tile.', mapHint:'Select a building, then place it on an empty tile.',
      news:'News', traits:'Traits', awards:'Awards', history:'History', all:'All', residential:'Residential', commercial:'Commercial', industrial:'Industrial', green:'Green', civic:'Civic', infrastructure:'Infrastructure',
      happiness:'Happiness', traffic:'Traffic', pollution:'Pollution', culture:'Culture', safety:'Safety', reputation:'Reputation', populationCapacity:'Residents / capacity: {pop} / {cap}. Housing and some buildings increase capacity.', nextUnlock:'Next Unlock', allPopUnlocks:'All population unlocks reached', landExpansionName:'Land Expansion', mayorPolicyName:'Mayor’s Desk policy', mayorPolicyUnlock:'Mayor’s Desk: {name}', atPopulation:'{name} · {n} pop',
      locked:'Locked', requires:'Requires {n} population.', utility:'utility', pop:'pop', completed:'Completed', unlocksAt:'Unlocks at {n} population', cost:'Cost ${n}', buildVerb:'Build',
      settingsSave:'Settings & Save', close:'Close', cityName:'City name', rename:'Rename', exportJson:'Export JSON', importJson:'Import JSON', newGame:'New Game',
      autosave:'Autosave runs every 10 seconds. Offline progress is capped at 8 hours.', language:'Language', english:'English', turkish:'Türkçe',
      newCity:'NEW CITY', startNew:'Start a new city?', replaceSave:'This will permanently replace the current local save on this device.', keepCity:'Keep current city', eraseStart:'Erase & Start New',
      helpTitle:'How to Play', helpIntro:'Grow a tiny settlement into a megacity without letting the budget or quality of life collapse.',
      helpBuild:'Build for growth', helpBuildText:'Homes raise population capacity. Shops and industry create income. Roads and services keep growth sustainable.',
      helpMoney:'Make money', helpMoneyText:'Commercial and industrial buildings generate the strongest income, but every service can add upkeep. Keep net income positive.',
      helpPop:'Grow population', helpPopText:'Housing adds capacity. Happiness, low pollution and manageable traffic make people arrive faster.',
      helpStats:'Watch the trade-offs', helpStatsText:'Traffic and pollution can drag happiness down. Parks, civic buildings and later mega projects help you recover.',
      helpDecisions:'Use the Mayor’s Desk', helpDecisionsText:'Policy choices can give immediate rewards or long-term modifiers. There is rarely one perfect answer.',
      helpIdle:'Idle & offline', helpIdleText:'The city progresses while the tab is open and for up to 8 hours while you are away. Use 2× when you want a faster session.',
      helpGoal:'Progression', helpGoalText:'Population unlocks new buildings, decisions, land expansions and mega projects. Traits and achievements record the kind of city you create.', helpGlossary:'Quick glossary', helpGlossaryText:'Capacity = how much growth your housing, jobs and infrastructure can support. Mayor’s Desk = policy decisions. News = random city events and local headlines.',
      gotIt:'Got it', decisionRequired:'Decision required', decisionMade:'Decision made', cityHallBrief:'CITY HALL BRIEF',
      noHeadlines:'No headlines yet.', historyBegins:'History begins here.', shapeDiscover:'??? — shape the city to discover this trait.', unlocked:'Unlocked',
      budgetSmall:'Budget too small', needMore:'Need ${n} more.', megaComplete:'Mega project complete', cityRenamed:'City renamed', importFailed:'Import failed',
      welcomeBack:'WELCOME BACK', whileAway:'While You Were Away', awayText:'Your city kept moving for {time}{cap}.', capApplied:' (8h cap applied)', backCity:'Back to the city', budget:'Budget',
      day:'Day {n}', settlement:'Settlement', town:'Town', smallCity:'Small City', regionalCity:'Regional City', metropolis:'Metropolis', megacity:'Megacity'
    },
    tr:{
      build:'İnşa', buildHint:'Bir yapı seçip haritada kareye tıkla', cityPulse:'Şehir Nabzı', growthStage:'Gelişim Aşaması',
      mayorDesk:'Başkanlık Masası', nextBrief:'Yeni dosya yakında', nextPolicyAt:'Sıradaki politika · {n} nüfus', allPoliciesHandled:'Tüm politika eşikleri tamamlandı', noDecision:'Bekleyen karar yok', noDecisionText:'Şehir geliştikçe ekibin yeni politika seçenekleri getirecek.',
      megaProjects:'Mega Projeler', megaSub:'Şehrin kaderini değiştiren yatırımlar', pause:'Duraklat', resume:'Devam Et', settings:'Ayarlar', howToPlay:'Nasıl Oynanır', liveStatus:'CANLI {n}×', pausedStatus:'DURAKLATILDI', pausedToast:'Simülasyon duraklatıldı', pausedToastText:'Zaman, gelir ve nüfus artışı donduruldu.', resumedToast:'Simülasyon devam ediyor', resumedToastText:'Şehir yeniden hareket halinde.', speedChanged:'Oyun hızı değişti', speedOne:'Simülasyon 1× hızında çalışıyor.', speedTwo:'Simülasyon 2× hızında çalışıyor.',
      bulldoze:'Yık', center:'Ortala', fitCity:'Şehri Sığdır', normalZoom:'Normal Görünüm', saveCityImage:'Şehir Resmini Kaydet', imageSaved:'Şehir resmi kaydedildi', imageSaveFailed:'Şehir resmi kaydedilemedi', versionLabel:'Sürüm', expandLand:'Araziyi Genişlet', landMax:'Arazi Maksimum', expandLandCost:'{n}×{n} Genişlet · ${cost}', expandLandLocked:'Arazi · {n} nüfus', expandLandTip:'Haritayı {n}×{n} boyutuna çıkar. Maliyet ${cost}; {pop} nüfus gerekli.', landLocked:'Genişleme kilitli', landExpanded:'Şehir sınırları genişledi', landExpandedText:'Harita artık {n} × {n}.', cityExpansion:'ŞEHİR GENİŞLEMESİ', expandTo:'{n} × {n} boyutuna genişletilsin mi?', expandConfirm:'${cost} karşılığında yeni arazi satın al. Mevcut şehir daha büyük {n} × {n} haritanın ortasında korunacak.', buyLand:'Araziyi Satın Al', cancel:'Vazgeç', placing:'{name} yerleştiriliyor — boş bir kare seç.', mapHint:'Bir yapı seç, sonra haritada boş bir kareye yerleştir.',
      news:'Haberler', traits:'Özellikler', awards:'Başarılar', history:'Tarihçe', all:'Tümü', residential:'Konut', commercial:'Ticaret', industrial:'Sanayi', green:'Yeşil', civic:'Kamu', infrastructure:'Altyapı',
      happiness:'Mutluluk', traffic:'Trafik', pollution:'Kirlilik', culture:'Kültür', safety:'Güvenlik', reputation:'İtibar', populationCapacity:'Sakinler / kapasite: {pop} / {cap}. Konutlar ve bazı yapılar kapasiteyi artırır.', nextUnlock:'Sıradaki Açılım', allPopUnlocks:'Tüm nüfus açılımları tamamlandı', landExpansionName:'Arazi Genişletme', mayorPolicyName:'Başkanlık politikası', mayorPolicyUnlock:'Başkanlık Masası: {name}', atPopulation:'{name} · {n} nüfus',
      locked:'Kilitli', requires:'{n} nüfus gerekli.', utility:'hizmet', pop:'nüfus', completed:'Tamamlandı', unlocksAt:'{n} nüfusta açılır', cost:'Maliyet ${n}', buildVerb:'İnşa Et',
      settingsSave:'Ayarlar & Kayıt', close:'Kapat', cityName:'Şehir adı', rename:'Yeniden Adlandır', exportJson:'JSON Dışa Aktar', importJson:'JSON İçe Aktar', newGame:'Yeni Oyun',
      autosave:'Otomatik kayıt 10 saniyede bir çalışır. Offline ilerleme en fazla 8 saattir.', language:'Dil', english:'English', turkish:'Türkçe',
      newCity:'YENİ ŞEHİR', startNew:'Yeni bir şehir kurulsun mu?', replaceSave:'Bu işlem bu cihazdaki mevcut yerel kaydın yerine yeni oyunu yazacak.', keepCity:'Mevcut şehri koru', eraseStart:'Sil & Yeni Başla',
      helpTitle:'Nasıl Oynanır', helpIntro:'Küçük bir yerleşimi büyüt; bütçeyi ve yaşam kalitesini çökertmeden megakente ulaş.',
      helpBuild:'Büyümek için inşa et', helpBuildText:'Konutlar nüfus kapasitesi sağlar. Ticaret ve sanayi gelir üretir. Yollar ve kamu hizmetleri büyümeyi sürdürülebilir tutar.',
      helpMoney:'Para kazan', helpMoneyText:'Ticaret ve sanayi en güçlü geliri üretir, fakat hizmetlerin gideri vardır. Net geliri mümkün olduğunca artıda tut.',
      helpPop:'Nüfusu büyüt', helpPopText:'Konutlar kapasite ekler. Yüksek mutluluk, düşük kirlilik ve makul trafik yeni nüfus gelişini hızlandırır.',
      helpStats:'Dengeleri takip et', helpStatsText:'Trafik ve kirlilik mutluluğu düşürür. Parklar, kamu yapıları ve ileride mega projeler şehri toparlamana yardım eder.',
      helpDecisions:'Başkanlık Masasını kullan', helpDecisionsText:'Politika seçimleri anlık ödüller veya süreli etkiler yaratabilir. Her zaman tek bir doğru cevap yoktur.',
      helpIdle:'Idle & offline', helpIdleText:'Şehir sekme açıkken ve sen yokken en fazla 8 saat ilerler. Daha hızlı oynamak istediğinde 2× kullan.',
      helpGoal:'İlerleme', helpGoalText:'Nüfus; yeni binaları, kararları, arazi genişletmelerini ve mega projeleri açar. Özellikler ve başarılar nasıl bir şehir kurduğunu kaydeder.', helpGlossary:'Kısa sözlük', helpGlossaryText:'Kapasite = konut, iş ve altyapının destekleyebildiği büyüme miktarı. Başkanlık Masası = politika kararları. Haberler = rastgele şehir olayları ve yerel başlıklar.',
      gotIt:'Tamamdır', decisionRequired:'Karar bekleniyor', decisionMade:'Karar verildi', cityHallBrief:'BELEDİYE DOSYASI',
      noHeadlines:'Henüz haber yok.', historyBegins:'Şehrin tarihi burada başlıyor.', shapeDiscover:'??? — şehri şekillendirerek bu özelliği keşfet.', unlocked:'Açıldı',
      budgetSmall:'Bütçe yetersiz', needMore:'${n} daha gerekli.', megaComplete:'Mega proje tamamlandı', cityRenamed:'Şehir yeniden adlandırıldı', importFailed:'İçe aktarma başarısız',
      welcomeBack:'TEKRAR HOŞ GELDİN', whileAway:'Sen Yokken', awayText:'Şehrin {time} boyunca ilerlemeye devam etti{cap}.', capApplied:' (8 saat sınırı uygulandı)', backCity:'Şehre dön', budget:'Bütçe',
      day:'Gün {n}', settlement:'Yerleşim', town:'Kasaba', smallCity:'Küçük Şehir', regionalCity:'Bölgesel Şehir', metropolis:'Metropol', megacity:'Megakent'
    }
  },
  data:{tr:{
    buildings:{
      house:['Sıra Evler','Yoğun başlangıç konutları.'],apartments:['Apartmanlar','Kare başına daha fazla vatandaş.'],tower:['Konut Kulesi','Şehir siluetini değiştiren konut.'],shops:['Mahalle Dükkânları','Yerel ticaret ve günlük ihtiyaçlar.'],mall:['Pazar Holü','Yoğun bölgesel perakende.'],office:['Ofis Bloğu','Yüksek değerli merkez işleri.'],workshop:['Atölye','Erken dönemin kaba ama faydalı sanayisi.'],factory:['Fabrika','Ciddi iş, ciddi duman.'],advanced:['İleri Sanayi','Daha temiz ve üretken sanayi.'],park:['Cep Parkı','Ağaçlar, banklar ve nefes alanı.'],garden:['Botanik Bahçesi','Büyük bir yeşil alan simgesi.'],clinic:['Klinik','Temel şehir sağlık hizmetleri.'],police:['Polis Merkezi','Suçu kontrol altında tutar.'],library:['Kütüphane','Bilgi ve kültür merkezi.'],school:['Mahalle Okulu','Eğitim kapasitesi ve mahalle yaşamı sağlar.'],recycling:['Geri Dönüşüm Merkezi','Atığı daha temiz büyümeye dönüştürür.'],cinema:['Sinema','Yoğun bir eğlence ve kültür noktası.'],firestation:['İtfaiye İstasyonu','Büyüyen şehir için acil durum kapsaması.'],transitHub:['Ulaşım Merkezi','Daha az arabayla daha çok insan taşır.'],hotel:['Büyük Otel','Turizm ve iş seyahatlerinden yüksek gelir.'],road:['Yol','Şehri görsel olarak birbirine bağlar.']
    },
    events:{
      festival:['Nehir Festivali','Müzik, yemek ve ışıklar sokakları dolduruyor.'],crisis:['Bölgesel Durgunluk','İşletmeler bütçeleri sıkıyor ve işe alımlar yavaşlıyor.'],tourists:['Turist Akını','Bir gezi videosu ziyaretçileri şehre dolduruyor.'],blackout:['Şebeke Arızası','Trafo arızası bazı mahalleleri karanlıkta bırakıyor.'],protest:['Merkezde Protesto','Sakinler artan kiraları protesto ediyor.'],invest:['Büyük Yatırım','Bir lojistik firması bölge ofisini açıyor.'],team:['Yerel Takım Şampiyon','Şehir sürpriz bir şampiyonluğu kutluyor.'],viral:['Şehir Viral Oldu','Tuhaf bir sokak görüntüsü internette patladı.'],art:['Yeni Sanat Dalgası','Boş duvarlar bir gecede duvar resimlerine dönüşüyor.'],storm:['Şiddetli Fırtına','Su basan yollar tüm şehri yavaşlatıyor.'],transit:['Otobüs Arıza Haftası','Bakım birikmesi toplu taşımayı vuruyor.'],students:['Öğrenci Akını','Yeni dönem için çok sayıda öğrenci geliyor.'],housing:['Emlak Patlaması','İnşaat talebi ve fiyatlar sıçrıyor.'],water:['Su Basıncı Sorunu','Eski borular yoğun saatlerde zorlanıyor.'],concert:['Büyük Konser','Turnedeki bir grup şehri tamamen dolduruyor.'],crime:['Suç Dalgası','Hırsızlıklardaki artış sakinleri endişelendiriyor.'],startup:['Yerel Girişim Başarısı','Şehirden çıkan bir girişim büyük yatırım alıyor.'],market:['Gece Pazarı','Kendiliğinden oluşan pazar haftalık geleneğe dönüşüyor.'],smog:['Smog Uyarısı','Durgun hava kirliliği şehrin üstünde tutuyor.'],cleanup:['Gönüllü Temizlik','Yüzlerce kişi şehir çapında temizliğe katılıyor.'],heritage:['Tarihi Keşif','Tadilat sırasında unutulmuş temeller bulunuyor.'],strike:['Ulaşım Grevi','Sürücüler anlaşma sağlanamayınca greve çıkıyor.'],food:['Yemek Sahnesi Gündemde','Yerel restoranlar ulusal basında yer buluyor.'],heat:['Sıcak Hava Dalgası','Rekor sıcaklar şehir hizmetlerini zorluyor.'],rain:['Mükemmel Yağmurlu Hafta','Temiz hava ve dolan rezervuarlar moralleri yükseltiyor.'],expo:['Bölgesel Fuar','İşletmeler ve ziyaretçiler otelleri dolduruyor.'],school:['Okul Başarısı Yükseldi','Yerel okullar yılların en iyi sonuçlarını alıyor.'],fire:['Depo Yangını','Ekipler tehlikeli sanayi yangınını kontrol altına alıyor.'],film:['Film Çekimi','Bir yapım ekibi merkezi film setine çeviriyor.'],sports:['Maraton Günü','Binlerce kişi trafiğe kapalı caddelerde koşuyor.'],tree:['Ağaçlandırma Seferberliği','Kampanyayla binlerce genç ağaç dikiliyor.'],hack:['Akıllı Şehir Arızası','Yazılım kesintisi park ve tabelaları aksatıyor.'],boom:['Bebek Patlaması','Bu sezon doğumlar keskin biçimde artıyor.'],museum:['Müze Bağışı','Bir koleksiyoncu önemli özel arşivini bağışlıyor.']
    },
    decisions:{
      parkParking:['Merkezde Boş Bir Arsa','Sakinler park, esnaf ise otopark istiyor.',['Parkı yap','Otopark yap']],
      transitBudget:['Otobüs Bütçesi','Ulaşım ekibi bir sonraki hizmet planı için yön istiyor.',['Seferleri artır','Aynı düzeyde tut','Seferleri azalt']],
      smallBusiness:['Ana Caddeye Destek','Yerel esnaf boş dükkânları doldurmak için belediyeden yardım istiyor.',['Küçük hibeler ver','Ruhsatları hızlandır','Müdahale etme']],
      tax:['Bütçe Baskısı','Mali işler vergi politikası istiyor.',['Vergiyi artır','Aynı bırak','Vergiyi düşür']],
      recycling:['Çöp Birikiyor','Temizlik ekipleri şehir çapında geri dönüşüm politikası öneriyor.',['Geri dönüşümü standart yap','Gönüllü kampanya başlat','Programı ertele']],
      streetUpgrade:['Bir Sokak, İki Öncelik','Yıpranmış bir konut sokağı bu yıl tek büyük iyileştirme alabilir.',['Sokak ağaçları dik','Aydınlatmayı geliştir','Sadece temel onarım']],
      rent:['Kiralar Yükseliyor','Büyüme konut maliyetlerini beklenenden hızlı artırıyor.',['Kiracıları koru','Yeni inşaatı teşvik et','Piyasaya bırak']],
      cultureFund:['Küçük Bir Kültür Fonu','Sanatçılar ve mekân sahipleri mütevazı bir kültür programı öneriyor.',['Yerel sanatı fonla','Halka açık etkinlikleri destekle','Bu yıl pas geç']],
      delivery:['Her Yerde Teslimat Kamyonu','Yük trafiği en yoğun ticaret sokaklarını tıkamaya başladı.',['Teslimat saatleri belirle','Erişimi serbest bırak','Düşük emisyon bölgesi kur']],
      industry:['Sanayi Genişleme Talebi','Geliştiriciler ağır sanayi için yeni alan istiyor.',['Onayla','Daha temiz plan iste']],
      schools:['Kalabalık Sınıflar','Genç ailelerin ilk dalgası yerel okulları zorluyor.',['Okul kapasitesini artır','Geçici sınıflar kullan','Genişlemeyi ertele']],
      tourism:['Şehri Haritaya Koyalım mı?','Turizm ofisi hafta sonu ziyaretçilerine yönelik kampanya istiyor.',['Kampanyayı başlat','Yerel halka odaklan','Parayı sakla']],
      nightlife:['Gece Yarısından Sonra','İşletmeler daha geç kapanmak istiyor.',['Şehir uyumasın','Saatleri değiştirme']],
      zoning:['Ne Kadar Yoğun Büyüyelim?','Plancılar yeni gelişim dalgası için imar yönü istiyor.',['Karma kullanımı teşvik et','Düşük yoğunluğu koru','Hızlı büyümeyi önceliklendir']],
      publicSafety:['Güvenlik Stratejisi','Polis şefi büyüyen şehir için üç seçenek sunuyor.',['Mahalle devriyeleri','Daha fazla kamera kur','Kadroyu sabit tut']],
      company:['Büyük Şirket, Büyük Talep','Büyük bir işveren taşınmak için vergi indirimi istiyor.',['İndirimi ver','Ayrıcalık yok']],
      energy:['Bir Sonraki Aşamayı Beslemek','Elektrik idaresi talep yeniden artmadan önce enerji stratejisi istiyor.',['Güneş çatısını destekle','Yedek üretim kur','Büyük yatırımı ertele']],
      heritage:['Eski Mahalle Riskte','Tarihi bir blok yüksek değerli projeye dönüşebilir.',['Koru','Yeniden geliştir']],
      cars:['Sıkışık Kavşak','Trafik mühendisleri iki farklı çözüm sunuyor.',['Yolları genişlet','Otobüs şeritleri']],
      housingScale:['Ölçekli Konut Büyümesi','Büyüme hızlanıyor. Plancılar bir sonraki dalga gelmeden konut stratejisi istiyor.',['Yeni konutları hızlandır','Önce altyapı kur','Büyümeyi kontrollü tut']],
      university:['Üniversite Önerisi','Eğitimciler kamu üniversitesi kampüsü öneriyor.',['Finanse et','Fazla pahalı']],
      metro:['Yeraltı Hırsı','Şehir erken metro planlamasına girmeli mi?',['Planlamayı başlat','Otobüslerle devam']],
      waterfront:['Nehir Kıyısı Kararı','Eski depoların yerine ne gelmeli?',['Halka açık kıyı','Lüks gelişim']]
    },
    projects:{university:['Şehir Üniversitesi','Büyük eğitim ve araştırma kampüsü.'],stadium:['Büyük Stadyum','Şehri bir araya getiren etkinlik motoru.'],metro:['Metro Sistemi','Caddelerin altında yüksek kapasiteli ulaşım.'],airport:['Uluslararası Havalimanı','Şehri küresel pazarlara bağlar.'],waterfront:['Nehir Kıyısı Yenilemesi','Parklar, yürüyüş yolları ve karma kullanım.'],skyscrapers:['Gökdelen Bölgesi','Yeni yüksek katlı iş merkezi.'],convention:['Kongre Merkezi','Fuarlar, etkinlikler ve büyük konferanslar.']}
,
    traits:{
      creative:['Yaratıcı Şehir','Kültür, şehrin itibarını taşıyor.','İtibar kazanımına +%8'],factory:['Fabrika Kasabası','Sanayi yerel ekonomiye hükmediyor.','Sanayi gelirine +%10'],green:['Yeşil Vaha','Parklar ve temiz hava şehri tanımlıyor.','Temel mutluluğa +5'],tourist:['Turist Mıknatısı','Ziyaretçiler doğrudan şehir için geliyor.','Ticari gelire +%6'],night:['Gece Hayatı Başkenti','Bu şehir gerçekten hiç uyumuyor.','Kültüre +4'],universityTown:['Üniversite Şehri','Öğrenciler şehrin karakterini değiştiriyor.','Kültüre +8'],spaghetti:['Şehir Spagettisi','Büyüme planlamayı geçmiş durumda.','Trafik eventleri daha olası'],car:['Araba Bağımlılığı','Geniş yollar, uzun yolculuklar, çok araba.','Kirliliğe +3'],culture:['Kültür Merkezi','Kütüphaneler ve etkinlikler burada önemli.','Mutluluğa +5'],industrialGiant:['Sanayi Devi','Üretim şehrin ana motoru.','Temel gelire +%12'],safe:['Güvenli Sokaklar','Sakinler kamusal alana güveniyor.','Mutluluğa +4'],wealthy:['Patlama Şehri','Para planlamacıların harcadığından hızlı akıyor.','İtibara +4'],dense:['Dikey Yaşam','Binlerce kişi kompakt kulelerde yaşıyor.','Nüfus artışına +%5'],metro:['Ulaşım Cenneti','Hızlı transit günlük hayatı değiştiriyor.','Trafiğe -12'],corporate:['Şirket Oyun Alanı','Büyük firmaların sıra dışı etkisi var.','Gelire +%8, mutluluğa -2'],water:['Nehir Şehri','Kıyı şehrin kimliğinin parçası olmuş.','İtibara +5'],sports:['Spor Şehri','Büyük kalabalıklar projektörlerin altında buluşuyor.','Mutluluğa +4'],global:['Küresel Geçit','Şehir dünyanın geri kalanına bağlı.','İtibara +8'],mega:['Mega Proje Alışkanlığı','Büyük yatırımlar rutin hale gelmiş.','Proje giderlerine -%5']
    },
    achievements:{
      pop1k:['Dört Haneli','1.000 nüfusa ulaş.'],pop10k:['Gerçek Şehir','10.000 nüfusa ulaş.'],pop100k:['Beton Okyanusu','100.000 nüfusa ulaş.'],million:['Belediye Milyoneri','Kasada $1.000.000 tut.'],happy90:['Sevilen Başkan','90 mutluluğa ulaş.'],traffic90:['Kilitledik!','90 trafiğe ulaş.'],clean:['Temiz Hava','5.000+ nüfusta kirliliği 10 altında tut.'],trait:['Karakterli Şehir','Bir şehir özelliği aç.'],traits5:['Kimlik Krizi','Beş şehir özelliği aç.'],mega:['Büyük Düşün','Bir mega proje tamamla.'],mega4:['Anıtsal','Dört mega proje tamamla.'],week:['Bir Hafta Sonra','7. güne ulaş.'],month:['Belediye Kurdu','30. güne ulaş.'],survivor:['Geri Dönüş','Eksiden sonra yeniden $10.000 üstüne çık.'],builder:['Kentsel Doku','50 yapı yerleştir.']
    }
  }},
  t(key, vars={}){ let s=(this.strings[this.lang()]||this.strings.en)[key] ?? this.strings.en[key] ?? key; for(const [k,v] of Object.entries(vars)) s=s.replaceAll('{'+k+'}',v); return s; },
  item(kind,id,field,fallback){ if(this.lang()!=='tr')return fallback; const row=this.data.tr[kind]?.[id]; if(!row)return fallback; if(kind==='decisions'){ if(field==='title')return row[0]; if(field==='text')return row[1]; return fallback; } if(field==='name'||field==='title')return row[0]??fallback; if(field==='effect')return row[2]??fallback; return row[1]??fallback; },
  choice(decisionId,index,fallback){ if(this.lang()!=='tr')return fallback; return this.data.tr.decisions?.[decisionId]?.[2]?.[index] || fallback; },
  stage(name){ const map={'Settlement':'settlement','Town':'town','Small City':'smallCity','Regional City':'regionalCity','Metropolis':'metropolis','Megacity':'megacity'}; return this.t(map[name]||name); }
};
